<hr style="margin-bottom: 40px;">

# NumPy exercises


Import Numpy Package

In [1]:

pip install numpy

Note: you may need to restart the kernel to use updated packages.Collecting numpy
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 320.0 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 460.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 16.8 MB/s eta 0:00:01
   ------ --------------------------------- 2.1/12.9 MB 26.5 MB/s eta 0:00:01
   ------------ --------------------------- 3.9/12.9 MB 35.8 MB/s eta 0:00:01
   ----------------- ---------------------- 5.7/12.9 MB 36.4 MB/s eta 0:00:01
   ----------------------- ---------------- 7.5/12.9 MB 37.0 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.9 MB 40.1 MB/s eta 0:00:01
   ---------------------------------- ----- 11.1/12.9 MB 43.7 MB/s e


[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: C:\Users\amand\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [7]:
import numpy as np

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

Crie uma matriz numpy de tamanho 10, preenchida com zeros.

In [111]:
np.zeros((2,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie um array numpy com valores variando de 10 a 49

In [267]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de 2 X 2 inteiros, preenchida com somente número 1.

In [268]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de 3 X 2 números flutuantes, preenchidos com número 1.

In [269]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, crie uma nova matriz numpy com a mesma forma e tipo de X, mas preenchida preenchida com número 1.

_Dica: ones_like()_

In [270]:
X = np.arange(4,dtype=int)
np.ones_like(X)


array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz numpy X, crie uma nova matriz numpy com a mesma forma e tipo de X, mas preenchida preenchida com zeros.

_Dica: zero_likes()_

In [271]:
X = np.array([[1,2,3],[4,5,6]], dtype=int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de 4X4 inteiros, preenchida com cincos.

In [272]:
np.full((4, 4), 5, dtype=int)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz numpy X, crie uma nova matriz numpy com a mesma forma e tipo de X, preenchida com setes.

In [273]:
X = np.array([[2,3],[6,2]],dtype=np.int16)
np.full_like(X,7)

array([[7, 7],
       [7, 7]], dtype=int16)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy de identidade 3 X 3 (1 na diagonal e o ao redor)

In [274]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy, preenchida com 3 valores inteiros aleatórios entre 1 e 10.

_Dica: random_

In [275]:
np.random.randint(1,11, size=(3,3))


array([[1, 8, 1],
       [2, 8, 9],
       [6, 2, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy **3 X 3 X 3**, preenchida com valores _float_ aleatórios.

In [276]:
np.random.rand(3,3,3)


array([[[0.57039867, 0.95031186, 0.18950337],
        [0.15950324, 0.57666614, 0.74402555],
        [0.89535998, 0.63212933, 0.34607734]],

       [[0.93633592, 0.59685266, 0.97640435],
        [0.92401063, 0.08659007, 0.78275556],
        [0.12109089, 0.31389725, 0.35735956]],

       [[0.79327118, 0.58530875, 0.6095061 ],
        [0.46283554, 0.33355108, 0.72637362],
        [0.95783878, 0.19202102, 0.25998387]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a lista X python, converta-a em uma matriz Y numpy

In [277]:
X= [1,2,3,4]
print(X, type(X))
Y = np.array(X)

[1, 2, 3, 4] <class 'list'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, faça uma cópia e armazene-a em Y.

_Dica: copy()_

In [278]:
X = np.array([5,2,3],dtype=np.int16)
Y = X.copy()
print(Y, id(Y))

[5 2 3] 2422230494512


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie um array numpy com números de 1 a 10

In [279]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie uma matriz numpy com os números ímpares entre 1 a 10

In [316]:
np.arange(1,11, 2)


array([1, 3, 5, 7, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Crie um array numpy com números de 1 a 10, em ordem decrescente.

In [352]:
np.arange (10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

*Crie uma matriz numpy 3 X 3, preenchida com valores variando de 0 a 8*

In [430]:
array_variando = np.arange(9)
matriz_3x3 = array_variando.reshape(3,3)
print (matriz_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


Dado o array X numpy, mostre seu primeiro elemento

In [497]:
X = np.array(['A','B','C','D','E'])
X = X[0]
print(X)

A


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre seu último elemento

In [530]:
X = np.array(['A','B','C','D','E'])
X = X[4]
print(X)


E


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre seus três primeiros elementos

In [564]:
X = np.array(['A','B','C','D','E'])
X = X[:3]
print (X)


['A' 'B' 'C']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre todos os elementos do meio

In [685]:
X = np.array(['A','B','C','D','E'])
X = X[1:-1]
print(X)

['B' 'C' 'D']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos na posição reversa

In [717]:
X = np.array(['A','B','C','D','E'])
X = X[::-1]
print(X)


['E' 'D' 'C' 'B' 'A']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos de posição ímpar

In [774]:
X = np.array(['A','B','C','D','E'])
X = X[1::2]
print(X)

['B' 'D']


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos da primeira linha

In [802]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X = X[0]
print(X)

[1 2 3 4]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os últimos elementos da linha

In [882]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X = X[:,-1]
print(X)


[ 4  8 12 16]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o primeiro elemento na primeira linha

In [933]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X = X[0,0]
print(X)

1


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o último elemento na última linha

In [985]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X = X[-1,-1]
print(X)

16


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os elementos da linha do meio

In [1009]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X = X[1:-1]
print(X)

[[ 5  6  7  8]
 [ 9 10 11 12]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os dois primeiros elementos nas duas primeiras linhas

In [1032]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X = X[:2,:2]
print(X)


[[1 2]
 [5 6]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre os dois últimos elementos nas duas últimas linhas

In [1075]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X = X[-2:,-2:]
print(X)


[[11 12]
 [15 16]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


Converta o lista de inteiros para numpy array do tipo float

_Dica: float_

In [1096]:
X = [-5, -3, 0, 10, 40]
np.array(X, dtype=float)

array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Inverta a matriz numpy fornecida (o primeiro elemento se torna o último)

In [1136]:
X = [-5, -3, 0, 10, 40]
X.reverse()
print(X)

[40, 10, 0, -3, -5]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Ordenar (classificar) o array numpy dado

_Dica: sort()_

In [1155]:
X = [0, 10, -5, 40, -3]
X.sort()
print(X)

[-5, -3, 0, 10, 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, defina o quinto elemento igual a 1

In [1173]:
X = np.zeros(10)
X[4] = 1
print(X)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, altere 50 por 40

In [1190]:
X = np.array([10, 20, 30, 50])
X[X == 50] = 40
print(X)

[10 20 30 40]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, altere a última linha com todos os 1

In [1206]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = 1
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

 Dada a matriz X numpy, troque o último item da última linha por 0

In [1278]:

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1,-1] = 0
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15  0]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, adicione 5 a cada elemento

In [1292]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X += 5
print(X)

[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


Dada a matriz X numpy, faça uma variável chamada mask que mostre verdadeiro para valores negativos e falso para valores positivos

In [1357]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X < 0
print(mask)

[ True False False  True False False False False  True False]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha os elementos negativos

In [1369]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X < 0
X = X[mask]
print(X)

[-1 -4 -9]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha números maiores que 5

In [1380]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X > 5
X = X[mask]
print(X)

[ 6 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha números maiores que a média dos elementos

_Dica: mean()_

In [1391]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
np.mean(X)
X = X[X > media]
print(X)

[ 5  6 10]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, obtenha números iguais a 2 ou 10

In [1400]:

X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = np.logical_or(X == 2, X == 10)
X = X[mask]
print(X)

[ 2 10]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


Dada a matriz X numpy, retorne True se nenhum de seus elementos for zero

_Dica: all()_

In [1401]:
X = np.array([-1, 2, 1, -4, 5, 6, 7, 8, -9, 10])
np.all(X !=0)

True

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, retorne True se algum de seus elementos for zero

_Dica: any()_

In [1402]:
X = np.array([0,0,0,0,0,0])
np.all(X == 0)

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

Dada a matriz X numpy, mostre a soma de seus elementos

_Dica: sum()_

In [1403]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X = sum(X)
print(X)

43


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dado o array X numpy, mostre o valor médio de seus elementos

_Dica: mean()_

In [1404]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
media = np.mean(X)
print(media)

3.7


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre a soma de suas colunas

remember !!!
- axis=0 columns 
- axis=1 rows

In [1405]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
np.sum(X, axis = 0)


array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o valor médio de suas linhas

In [1406]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
np.mean(X, axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

Dada a matriz X numpy, mostre o valor máximo de seus elementos

In [1407]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
np.max(X)

10